workflow:
  name: "test_pipeline"
  project: "proj_simscience"
  queue: "all.q"
  output_directory: "/ihme/homes/albrja/scratch/test_pipeline_v2"
  steps:
    - name: "step1_echo"
      command: "echo 'step 1 complete'"
      resources:
        memory_gb: 1
        runtime: "00:01:00"
    - name: run_simulation
      type: simulation
      resources:
        memory_gb: 16
        runtime: "01:00:00"
      args:
        model_specification: src/vivarium_gates_mncnh/model_specifications/model_spec.yaml
        branch_configuration: src/vivarium_gates_mncnh/model_specifications/branches/scenarios.yaml
        result_directory: /ihme/homes/albrja/scratch/
    - name: "step3_echo"
      command: "echo 'step 3 complete'"
      resources:
        memory_gb: 1
        runtime: "00:01:00"
