workflow:
  name: "test_pipeline"
  project: "proj_simscience"
  queue: "all.q"
  output_directory: "/ihme/homes/albrja/scratch/test_pipeline"
  steps:
    - name: "step1_echo"
      command: "echo 'step 1 complete'"
      resources:
        memory_gb: 1
        runtime: "00:01:00"
    - name: run_simulation
      type: simulation
      resources:  # task runner resources
        memory_gb: 4
        runtime: "00:20:00"
      args:
        model_specification: src/vivarium_gates_mncnh/model_specifications/model_spec.yaml
        branch_configuration: src/vivarium_gates_mncnh/model_specifications/branches/scenarios.yaml
    - name: "tests"
      type: pytest
      environment: art
      resources:
        memory_gb: 2
        runtime: "00:01:00"
        cores: 2
      args:
        path: /tests/automated_v_and_v/test_measures.py
        runslow: true
        numprocesses: 2
