workflow:
  name: "test_pipeline"
  project: "proj_simscience"
  queue: "all.q"
  output_directory: /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/results/test_workflow
  steps:
    # - name: "check_clean_working_tree"
      
    - name: "paf_sim"
      type: python
      resources:
        memory_gb: 16
        runtime: "00:30:00"
      args:
        path: src/vivarium_gates_mncnh/data/lbwsg_paf/code/run_paf_sim.py
        keyword_args:
          a: test_workflow
          l: "Ethiopia"
    # - name: "hemoglobin_effects_birth_effect"
    #   command: "python parallel_runner.py --workers 4 -- generate_birth_effects.py"
    #   resources:
    #     memory_gb: 1
    #     runtime: "06:00:00"

    # - name: "hemoglobin_effects_sepsis"
    #   command: "python parallel_runner.py --workers 4 -- generate_nn_sepsis_effects.py"
    #   resources:
    #     memory_gb: 1
    #     runtime: "02:00:00"

    # - name: "hemoglobin_maternal_disorders_sim"
    #   type: python
    #   resources:
    #     memory_gb: 1
    #     runtime: "00:20:00"
    #   args:
    #     path: src/vivarium_gates_mncnh/data/hgb_pafs_maternal_disorders/code/generate_pafs.py

    - name: "make_artifacts"
      environment: vivarium_gates_mncnh_artifact
      command: 'bash -lc "yes y | make_artifacts -l all -o /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/test_workflow/"'
      resources:
        memory_gb: 1
        runtime: "01:00:00"
    
    # - name: "commit_and_tag"
      
    - name: run_simulation
      type: simulation
      resources:  # task runner resources
        memory_gb: 4
        runtime: "00:20:00"
      args:
        model_specification: src/vivarium_gates_mncnh/model_specifications/model_spec.yaml
        branch_configuration: src/vivarium_gates_mncnh/model_specifications/branches/scenarios.yaml
    - name: "tests"
      type: pytest
      environment: vivarium_gates_mncnh_artifact
      resources:
        memory_gb: 2
        runtime: "01:00:00"
        cores: 2
      args:
        path: 
          - tests/
        runslow: true
    - name: "tests"
      type: pytest
      resources:
        memory_gb: 2
        runtime: "00:30:00"
        cores: 2
      args:
        path: 
          - tests/
        runslow: true
