workflow:
  name: "test_pipeline"
  project: "proj_simscience"
  queue: "all.q"
  output_directory: /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/results/model33.1
  steps:
    - name: "check_clean_working_tree"
      type: python
      resources:
        memory_gb: 1
        runtime: "00:01:00"
      args:
        path: src/vivarium_gates_mncnh/tools/check_working_tree.py

    # NOTE: It is expected a user would manually do this between workflows
    # - name: "commit_and_tag"
    #   type: python
    #   resources:
    #     memory_gb: 1
    #     runtime: "00:01:00"
    #   args:
    #     path: src/vivarium_gates_mncnh/tools/commit_and_tag.py
    #     positional_args:
    #       - "10.0"

    - name: run_simulation_ethiopia
      type: simulation
      resources:  # task runner resources
        memory_gb: 4
        runtime: "00:20:00"
      args:
        model_specification: src/vivarium_gates_mncnh/model_specifications/model_spec.yaml
        branch_configuration: src/vivarium_gates_mncnh/model_specifications/branches/scenarios.yaml
        artifact_path: /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/test_workflow/ethiopia.hdf

    - name: run_simulation_nigeria
      type: simulation
      resources:  # task runner resources
        memory_gb: 4
        runtime: "00:20:00"
      args:
        model_specification: src/vivarium_gates_mncnh/model_specifications/model_spec.yaml
        branch_configuration: src/vivarium_gates_mncnh/model_specifications/branches/scenarios.yaml
        artifact_path: /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/test_workflow/nigeria.hdf

    - name: run_simulation_pakistan
      type: simulation
      resources:  # task runner resources
        memory_gb: 4
        runtime: "00:20:00"
      args:
        model_specification: src/vivarium_gates_mncnh/model_specifications/model_spec.yaml
        branch_configuration: src/vivarium_gates_mncnh/model_specifications/branches/scenarios.yaml
        artifact_path: /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/test_workflow/pakistan.hdf
    
    - name: "tests_artifact"
      type: pytest
      environment: vivarium_gates_mncnh_artifact
      resources:
        memory_gb: 2
        runtime: "01:00:00"
        cores: 4
      args:
        path: 
          - tests/
        runslow: true
        k: "results"
